name: Linux Build

on: [push, pull_request]

# At one point, "Build Anthem" and "Generate AppImage" both added the Qt directory to the path, but install-qt-action does that now.

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Download Dependencies
      run: |
           sudo apt install libxkbcommon-x11-0 -y
           sudo apt install libgl1-mesa-dev -y
           sudo apt install libxcb-icccm4-dev -y
           sudo apt install libxcb-image0-dev -y
           sudo apt install libxcb-keysyms1-dev -y
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
    - name: Build Anthem
      run: |
           cd $GITHUB_WORKSPACE/src
           cmake .
           mkdir build
           cd build
           cmake --build .. --target all
    - name: Generate AppImage
      run: |
#  sudo apt install tree
#  tree
           cd $GITHUB_WORKSPACE/src/build
           export QML_SOURCES_PATHS=$GITHUB_WORKSPACE/src
           wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
           wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
           chmod +x linuxdeploy*.AppImage
           ./linuxdeploy-x86_64.AppImage --appdir AppDir -e ../Anthem -i ../actions/linux/Anthem.png -d ../actions/linux/anthem.desktop --plugin qt --output appimage
           mkdir upload
           mv ./Anthem*.AppImage ./upload
    - uses: actions/upload-artifact@master
      with:
        name: Anthem - Linux build
        path: 'build/upload'
