name: Windows Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download Qt
      run: '. "${env:GITHUB_WORKSPACE}\actions\windows\get-qt.ps1"'
      shell: powershell
    - name: Install Qt
      run: '%GITHUB_WORKSPACE%\qt-install.exe --script .\actions\installer-noninteractive-windows.qs --verbose'
    - name: Build Anthem
      run: '. "${env:GITHUB_WORKSPACE}\actions\windows\build-anthem.ps1"'
