name: Windows Build (MinGW)

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    # - name: Install Qt
    #   uses: jurplel/install-qt-action@v2
    #   with:
    #     version: 5.14.1
    #     arch: win64_mingw73
    # - name: Build Anthem
    #   run: '. "${env:GITHUB_WORKSPACE}\actions\windows\build-anthem-mingw.ps1"'
    #   shell: powershell
    # - name: Run tests
    #   run: D:\Anthem\Main.exe --test
    #   shell: powershell
    #   continue-on-error: true
    # - uses: actions/upload-artifact@master
    #   with:
    #     name: Anthem - Windows build
    #     path: 'D:\Anthem'
