name: Linux Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Download repository
      run: |
           git clone --single-branch --branch jake-dev https://github.com/SecondFlight/daw-prototype.git
           cd daw-prototype
           git submodule update --init --recursive
           cd ../
    - name: Download Qt
      run: wget http://qt.mirror.constant.com/archive/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
    - name: Install Qt       
      run: |
           chmod +x ./qt-opensource-linux-x64-5.13.0.run
           ./qt-opensource-linux-x64-5.13.0.run --script ./daw-prototype/actions/installer-noninteractive.qs --platform minimal
    - name: Build Anthem and make appimage
      run: |
           export PATH=$PATH:/qt/5.13.0/gcc_64/bin/
           mkdir build
           cd build 
           qmake ../daw-prototype/Prototyping.pro
           make
           make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
           cd
           wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
           chmod a+x linuxdeployqt-continuous-x86_64.AppImage
           ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
           
