name: Linux Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Download submodules
      run: git submodule update --init --recursive
    - name: Download Qt
      run: wget http://qt.mirror.constant.com/archive/qt/5.13/5.13.0/qt-opensource-linux-x64-5.13.0.run
    - name: Install Qt       
      run: |
           chmod +x ./qt-opensource-linux-x64-5.13.0.run
           ./qt-opensource-linux-x64-5.13.0.run --script ./actions/installer-noninteractive.qs --platform minimal
    - name: Build Anthem and make appimage
      run: |
           export PATH=$PATH:/qt/5.13.0/gcc_64/bin/
           mkdir build
           cd build 
           mkdir appdir
           qmake ../Prototyping.pro
           make
           make -j$(nproc) install ; find appdir/
           echo "Current Directory"
           ls -la
           echo "Main Directory"
           ls -la ./Main
           echo "appdir directory" 
           ls -la ./appdir

